package com.markreader.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF2A5BD7)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDCE2FF)
val LightOnPrimaryContainer = Color(0xFF001849)
val LightSecondary = Color(0xFF5B5D72)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE0E1F9)
val LightOnSecondaryContainer = Color(0xFF171A2C)
val LightTertiary = Color(0xFF7A4A8E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFF9D7FF)
val LightOnTertiaryContainer = Color(0xFF2F003F)
val LightBackground = Color(0xFFF9F9FF)
val LightOnBackground = Color(0xFF1A1B1F)
val LightSurface = Color(0xFFF9F9FF)
val LightOnSurface = Color(0xFF1A1B1F)
val LightSurfaceVariant = Color(0xFFE2E2EC)
val LightOnSurfaceVariant = Color(0xFF45464F)
val LightOutline = Color(0xFF757680)

val DarkPrimary = Color(0xFFB5C4FF)
val DarkOnPrimary = Color(0xFF002A78)
val DarkPrimaryContainer = Color(0xFF0040A7)
val DarkOnPrimaryContainer = Color(0xFFDCE2FF)
val DarkSecondary = Color(0xFFC3C4DD)
val DarkOnSecondary = Color(0xFF2D3044)
val DarkSecondaryContainer = Color(0xFF44475C)
val DarkOnSecondaryContainer = Color(0xFFE0E1F9)
val DarkTertiary = Color(0xFFE6B6F7)
val DarkOnTertiary = Color(0xFF48205D)
val DarkTertiaryContainer = Color(0xFF613775)
val DarkOnTertiaryContainer = Color(0xFFF9D7FF)
val DarkBackground = Color(0xFF121318)
val DarkOnBackground = Color(0xFFE3E2E8)
val DarkSurface = Color(0xFF121318)
val DarkOnSurface = Color(0xFFE3E2E8)
val DarkSurfaceVariant = Color(0xFF45464F)
val DarkOnSurfaceVariant = Color(0xFFC6C6D0)
val DarkOutline = Color(0xFF8F909A)

// Light surface container tones
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF3F3F9)
val LightSurfaceContainer = Color(0xFFEDEDF3)
val LightSurfaceContainerHigh = Color(0xFFE7E7ED)
val LightSurfaceContainerHighest = Color(0xFFE2E2E7)

// Dark surface container tones
val DarkSurfaceContainerLowest = Color(0xFF0D0E13)
val DarkSurfaceContainerLow = Color(0xFF1A1B20)
val DarkSurfaceContainer = Color(0xFF1E1F25)
val DarkSurfaceContainerHigh = Color(0xFF292A2F)
val DarkSurfaceContainerHighest = Color(0xFF33343A)

val AmoledBackground = Color(0xFF000000)
val AmoledSurface = Color(0xFF000000)
val AmoledOnSurface = Color(0xFFE6E6EB)

val SepiaPrimary = Color(0xFF7A4E2B)
val SepiaOnPrimary = Color(0xFFFFFFFF)
val SepiaPrimaryContainer = Color(0xFFFFDCBF)
val SepiaOnPrimaryContainer = Color(0xFF2E1500)
val SepiaSecondary = Color(0xFF6F5B4C)
val SepiaOnSecondary = Color(0xFFFFFFFF)
val SepiaSecondaryContainer = Color(0xFFF7DED0)
val SepiaOnSecondaryContainer = Color(0xFF271B12)
val SepiaTertiary = Color(0xFF4F6B4A)
val SepiaOnTertiary = Color(0xFFFFFFFF)
val SepiaTertiaryContainer = Color(0xFFD1F0C9)
val SepiaOnTertiaryContainer = Color(0xFF0C200B)
val SepiaBackground = Color(0xFFF6EDE3)
val SepiaOnBackground = Color(0xFF201A17)
val SepiaSurface = Color(0xFFF6EDE3)
val SepiaOnSurface = Color(0xFF201A17)
val SepiaSurfaceVariant = Color(0xFFE8D7CA)
val SepiaOnSurfaceVariant = Color(0xFF51443B)
val SepiaOutline = Color(0xFF83746B)
